### ISSUE TITLE
Why executing 2 times each Job ?

### ISSUE THREAD

**Issue by JoaoVictorSarzi** [Webador/SlmQueueDoctrine#178]
I am having a problem where a new job is pushed and exeuted 2 times nt only one ?
How can i fix this ?

$this->queue('default')
            ->push('Admin\Job\EmailJob', [
                'to' => 'email@teste.com.br',
                'subject' => 'Queue EmailJob Test',
                'message' => $htmlMessage
            ],['delay' => 10]);

The status change to 2 and after this deleted from the table.

**Comment by roelvanduijnhoven** [comment]
@JoaoVictorSarzi A status of `2` signals that the jobs is _running_. Once done, it will be removed from the queue. So it will really only run once.

**Comment by JoaoVictorSarzi** [comment]
@roelvanduijnhoven i am sendind an email form PhpMailer, but always i run a job this send 2 e-mails not only one.

**Comment by roelvanduijnhoven** [comment]
The code you shown above is correct, and should only send once. So probably something else is off! Hard to say what, without more information. If after analysis, you still believe there to be a bug, let me know.

**Comment by JoaoVictorSarzi** [comment]
@roelvanduijnhoven I am tryng to find out. I test again with a HelloWorld job, and taht print 2 times on the prompt.
I install SlmQueue, SlmQueueDoctrine, add the slm_queue.global.php and create a Entity to use on doctirne migrations. Only This.
The execute method on Job is called only when worker get this job on the database?

**Comment by roelvanduijnhoven** [comment]
@JoaoVictorSarzi Not sure, sorry! The _execute_ method should indeed only be called once.
