### ISSUE TITLE
Using stale data.

### ISSUE THREAD

**Issue by jarrettj** [Webador/SlmQueueDoctrine#181]
Hi,

Good day.

Is there any reason why the data retrieved would be stale? 

Use Case:
- We are using the queue to send out emails to users. 
- We update the user to be disabled.
- The user still receives emails because the users state seems to be stale.
- Restarting the process, and the updated state is retrieved from the database.

Any ideas as to why this would happen? We are running the queue without redis cache, instead using array cache. As with redis cache we had other issues relating to segmentation faults due to memory limits.

Regards,
Jarrett

**Comment by basz** [comment]
Without more info it seems hard to tell what's going on.

Maybe be a transaction that is not committed...

What do you mean by "the data"?
Does the payload of the job contains user data. For a mail queue that would seem logical. When send to the queue a mail would be sent regardless of the actual use state unless there are guards in place to prevent that. But why would there. Email queues are typically not long lived queues.

Also maybe clear the entity manager in jobs.

**Comment by jarrettj** [comment]
First off, thanks for the quick response, much appreciated. Apologise, let me try and explain that better. 

Once the queue process is started, any update to the database is not seen by the queue process. Does that make sense? 

My queue process has access to the doctrine entity manager which accesses the database to query for, lets say a list of users to send an email to. The email part is fine. The issue is, if I disable/delete a user on the website, the queue process does not see that update. Until I restart the queue. 

When you say, clear the entity manager, do you mean, before making a request to the database to clear it? Let me give that a shot quickly.  

Regards,
Jarrett

**Comment by jarrettj** [comment]
Oh no! It was a logic issue in my job :)
