### ISSUE TITLE
Cronjob Safe Queue Processing

### ISSUE THREAD

**Issue by kenkataiwa** [Webador/SlmQueueDoctrine#37]
I've read the following in the documentation:

"Warning : In previous versions of SlmQueueDoctrine the worker would quit if there where no jobs available for processing. That meant you could safely create a cronjob that would start a worker every minute. If you do that now you will quickly run out of available resources."

I'm curious as to why you would abandon this particular feature. Most/all of the queued jobs are pushed automatically, why then should someone manual run/process the queue every time? Could you perhaps add this feature back or at least explain why you abandoned it in the first place. 

By the way if I'm missing something, maybe a new way to set up Cronjobs for SlimQueueDoctrine, could you share an example.
Thank you.

**Comment by barannd** [comment]
Can someone tell me how I have to configure a cronjob to work with SlmQueue? I'm not able to install tools like supervisor on my server.

**Comment by basz** [comment]
```
* * * * * /path/to/php /path/to/public/index.php queue doctrine queueName --start
```
Configured such that it will terminate after x jobs or x time to avoid running out of available resources

**Comment by barannd** [comment]
Ahh ok. Didn't recognize it from the comments above. Thanks for the super fast answer!
