### ISSUE TITLE
Migration script to update existing queue to v4

### ISSUE THREAD

**Issue by roelvanduijnhoven** [Webador/SlmQueueDoctrine#92]
_This may not be the best place to put. Nontheless I could not find a better location._

I am in the process of updating slmqueue to v4. The queue is populated with almost 20k records, so I wanted to preserve them. The solution as mentioned in the CHANGELOG does not work because it is non-trivial to run two versions of slmqueue next to each other.

Instead I chose to manually update the queue using a migration script. I ended up with: https://gist.github.com/roelvanduijnhoven/8eea449d255ca4b8cafb

As other people might face the same problem I though I would share it.

**Comment by basz** [comment]
I'm still running v3 and in the process of going to v4. 

I think data is already in this format? Am I missing something?

```
composer info
slm/queue                                        2.1.0                     Laminas module that integrates with various queue management systems
slm/queue-doctrine                               3.0.2                     Laminas Framework module that integrates Doctrine as queuing system
```

**Comment by roelvanduijnhoven** [comment]
@basz Lol a comment from 2015! 

I'm talking about the migration mentioned in release v.0.40, see https://github.com/Webador/SlmQueue/releases/tag/0.4.0-beta3. So this is really old stuff!

You are right, that nothing recently changed here.

I'll be sure to close this and other dead / outdated issues.
